import type { System, SupportingModule } from "@/types";

export const systems: System[] = [
  {
    id: "sales-recovery",
    name: "AI Sales & Recovery System",
    outcome:
      "Convert more high-intent shoppers and recover revenue that would otherwise be lost.",
    capabilities: [
      "AI product guidance",
      "Personalized product recommendations",
      "Abandoned-cart conversations",
      "WhatsApp and Instagram follow-up",
      "Lead qualification",
      "Objection handling",
      "Back-in-stock and price-drop alerts",
      "High-value lead routing",
      "Human handoff for complex conversations",
    ],
    commonTriggers: [
      "A cart is abandoned before checkout",
      "A shopper asks a product question outside working hours",
      "A high-value lead engages but doesn't convert",
    ],
    exampleWorkflow: [
      "Shopper browses and exits without purchasing",
      "AI reviews cart contents, product data, and delivery rules",
      "A personalized WhatsApp or email follow-up is generated",
      "Objections are classified and addressed",
      "Complex or high-value conversations are handed to a person",
    ],
    integrations: ["Shopify", "WooCommerce", "WhatsApp", "Instagram", "Klaviyo", "Gmail"],
    metrics: [
      "Qualified conversations",
      "Recovered carts",
      "Conversion from assisted sessions",
      "Response time",
      "Revenue influenced",
      "Handoff rate",
    ],
    bestFitFor:
      "Brands losing high-intent shoppers to slow responses or generic cart-recovery messages.",
    ctaLabel: "Explore the Sales System",
  },
  {
    id: "customer-experience",
    name: "AI Customer Experience System",
    outcome:
      "Give customers faster, consistent support without forcing your team to answer every repetitive request.",
    capabilities: [
      "Order tracking",
      "Delivery questions",
      "Returns and exchange guidance",
      "Product and policy questions",
      "Customer identification",
      "Multilingual responses",
      "Sentiment and urgency detection",
      "Ticket categorization",
      "Human escalation",
      "Quality review and conversation analytics",
    ],
    commonTriggers: [
      "A customer asks about order status or delivery",
      "A return or exchange request comes in",
      "A repetitive policy question arrives outside working hours",
    ],
    exampleWorkflow: [
      "Customer message is received across a support channel",
      "AI identifies the customer and retrieves the relevant order",
      "Policy and business rules are checked before a response is generated",
      "Routine requests are resolved directly",
      "Sensitive or unclear cases are escalated to a person",
    ],
    integrations: ["Gorgias", "Gmail", "Outlook", "WhatsApp", "Shopify", "WooCommerce"],
    metrics: [
      "First-response time",
      "Resolution rate",
      "Automated resolution rate",
      "Ticket volume",
      "Escalation rate",
      "Customer satisfaction",
      "Cost per resolution",
    ],
    bestFitFor:
      "Teams answering the same order, delivery, and policy questions every day across multiple channels.",
    ctaLabel: "Explore the CX System",
  },
  {
    id: "operations-intelligence",
    name: "AI Operations Intelligence System",
    outcome: "Turn scattered commerce data into alerts, dashboards, and daily decisions.",
    capabilities: [
      "Unified order data",
      "Inventory alerts",
      "Low-stock and unusual-demand alerts",
      "Channel profitability",
      "Contribution-profit reporting",
      "Delivery-cost visibility",
      "Product performance",
      "Daily and weekly executive summaries",
      "Data-quality checks",
      "Sales forecasting support",
      "Read-only AI business analyst",
      "Automated operational reporting",
    ],
    commonTriggers: [
      "Inventory data lives in spreadsheets that need manual reconciliation",
      "Channel or product profitability is unclear without manual work",
      "Reports explain what already happened instead of what needs attention",
    ],
    exampleWorkflow: [
      "Order, inventory, and channel data are unified into one layer",
      "Data-quality checks flag inconsistencies automatically",
      "Alerts are generated for stock, demand, or profitability exceptions",
      "A daily or weekly summary is delivered to the team",
      "A read-only AI analyst can answer follow-up questions on the data",
    ],
    integrations: ["Shopify", "WooCommerce", "Google Sheets", "Microsoft 365", "ERPs", "Marketplaces"],
    metrics: [
      "Manual hours removed",
      "Reporting time",
      "Inventory exceptions",
      "Data-quality issues",
      "Contribution profit",
      "Channel performance",
      "Decision response time",
    ],
    bestFitFor:
      "Operations teams relying on spreadsheets and manual checks to understand inventory, channels, or profitability.",
    ctaLabel: "Explore the Operations System",
  },
];

export const supportingModules: SupportingModule[] = [
  { name: "AI review-response system" },
  { name: "Product-content automation" },
  { name: "Customer feedback intelligence" },
  { name: "Lead-to-CRM automation" },
  { name: "Inventory exception alerts" },
  { name: "Executive reporting assistant" },
  { name: "Internal knowledge assistant" },
  { name: "Product catalog enrichment" },
  { name: "Social inbox triage" },
  { name: "Marketplace order consolidation" },
];
